stages:
  - build-staging
  - build-prod

deploy-develop:
  stage: build-staging
  tags:
    - staging.gamisodes.com
  only:
    - dev
  script:
    - cd /home/ubuntu/gamisodesnft
    - pwd
    - git checkout --force dev
    - git reset --hard HEAD
    - git pull origin dev

deploy-preprod:
  stage: build-prod
  tags:
    - prod.gamisodes.com
  script:
    - cd /home/ubuntu/gamisodesnft
    - pwd
    - git checkout --force main
    - git reset --hard HEAD
    - git pull origin main

  only:
    - main


